### ISSUE TITLE
No traces of backups

### ISSUE THREAD

**Issue by evil-shrike** [xfalcox/discourse-backups-to-dropbox#2]
Hi.
I installed the plugin, created an app in Dropbox and set up settings (enabled/api key). But I can't see any backups and no any mentions of "dropbox" in production.log. So it seems not working.

Is it ok that the app has development status? 
![image](https://cloud.githubusercontent.com/assets/1203230/23335954/ec4dbb18-fbd1-11e6-9db7-4e7532abd204.png)

Also a Dropbox app has key and secret , but the plugin only asks for key, is it correct?

How to find out what can be wrong with the plugin?

**Comment by xfalcox** [comment]
> Also a Dropbox app has key and secret , but the plugin only asks for key, is it correct?

As the `discourse backups to dropbox api key` help text say:

> Your Dropbox Dropbox Generated Access Token

You need to use the **Generated Access Token**
