### ISSUE TITLE
domain_name gem version clash

### ISSUE THREAD

**Issue by tarragon** [xfalcox/discourse-backups-to-dropbox#4]
Howdy,

I recently found that this plugin was causing an upgrade to 1.8.3 to fail, with the following:

```
I, [2017-07-12T02:29:45.539362 #13]  INFO -- : > cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate'
rake aborted!
Gem::LoadError: can't activate domain_name-0.5.20170404, already activated domain_name-0.5.25
```

It looks like a recent change here has caused a conflict with the version of domain_name in Discourse:stable?

**Comment by xfalcox** [comment]
Yes, please use the `stable` branch of the plugin to use the `stable` version of Discourse.

**Comment by tarragon** [comment]
Thanks, adding `git clone --branch stable https://github.com/xfalcox/discourse-backups-to-dropbox.git` to the plugins section fixed the issue.
